name: Build Zed Nightly 3

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: zed-industries/zed
          ref: main

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: wasm32-wasi

      - name: Build release
        run: cargo build --release

      - name: Set Release Date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: zed-release
          path: target/release/zed.exe

      - uses: actions/download-artifact@v4
        with:
          name: zed-release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.CURRENT_DATE }}
          tag_name: ${{ env.CURRENT_DATE }}
          draft: false
          make_latest: true
          files: target/release/zed.exe
