name: Build Zed for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Zed repository
      uses: actions/checkout@v3
      with:
        repository: zed-industries/zed
        fetch-depth: 1

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-wasi

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Setup Visual Studio Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build Zed
      run: |
        cargo build --release --workspace

    - name: Run tests
      run: |
        cargo test --workspace

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: zed-windows
        path: target/release/zed.exe
